[package]
name = "chain-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Block executor wrapping MoveVM"

[lints]
workspace = true

[dependencies]
blake3.workspace = true
chain-engine-api = { path = "../engine-api", version = "0.1.0" }
chain-modules = { path = "../modules", version = "0.1.0" }
chain-state = { path = "../state", version = "0.1.0" }
chain-types = { path = "../types", version = "0.1.0" }
move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-bytecode-verifier-meter.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-runtime.workspace = true
ruint = "1"
tempfile.workspace = true
better_any = "0.1.1"
smallvec = "1"
bcs = "0.1.6"

[dev-dependencies]
blst.workspace = true
ed25519-dalek.workspace = true
