[package]
name = "chain-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "BFT engine, fork choice, evidence detection"

[lints]
workspace = true

[dependencies]
chain-types = { path = "../chain-types", version = "0.1.0" }
malachite-core-consensus.workspace = true
malachite-core-driver.workspace = true
malachite-core-types.workspace = true

[dev-dependencies]
blst.workspace = true
malachite-metrics.workspace = true
malachite-test.workspace = true
