[package]
name = "chain-mempool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tx admission, eviction, replacement"

[lints]
workspace = true

[dependencies]
chain-state = { path = "../chain-state", version = "0.1.0" }
chain-types = { path = "../chain-types", version = "0.1.0" }

[dev-dependencies]
ed25519-dalek.workspace = true
