# config.toml

# Token Related
NanoPerThrylos = 10000000
InitialTotalSupply = 120000000

# Staking Related
AnnualStakeReward = 48000000000000
DailyStakeReward = 131506849
MinimumStakeAmount = 400000000
MinStakePercentage = 0.1

# Time Related
RewardDistributionTimeInterval = 86400

# Delegation Related
DelegationRewardPercent = 0.5

# --- ADDED Gas Fee Entries ---
min_gas_fee = 10000       # nanoTHR (0.001 THR)
max_gas_fee = 1000000    # nanoTHR (0.1 THR)
default_gas_fee = 50000 # nanoTHR (0.005 THR)
