// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BalanceResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsBalanceResponse(buf []byte, offset flatbuffers.UOffsetT) *BalanceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BalanceResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishBalanceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBalanceResponse(buf []byte, offset flatbuffers.UOffsetT) *BalanceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BalanceResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBalanceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BalanceResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BalanceResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BalanceResponse) Balance() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *BalanceResponse) MutateBalance(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func BalanceResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BalanceResponseAddBalance(builder *flatbuffers.Builder, balance float64) {
	builder.PrependFloat64Slot(0, balance, 0.0)
}
func BalanceResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
