// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EmptyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEmptyRequest(buf []byte, offset flatbuffers.UOffsetT) *EmptyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EmptyRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishEmptyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEmptyRequest(buf []byte, offset flatbuffers.UOffsetT) *EmptyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EmptyRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEmptyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EmptyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EmptyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func EmptyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EmptyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
