// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPendingTransactionsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPendingTransactionsRequest(buf []byte, offset flatbuffers.UOffsetT) *GetPendingTransactionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPendingTransactionsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPendingTransactionsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPendingTransactionsRequest(buf []byte, offset flatbuffers.UOffsetT) *GetPendingTransactionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPendingTransactionsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPendingTransactionsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPendingTransactionsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPendingTransactionsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func GetPendingTransactionsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GetPendingTransactionsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
