// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetStatsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetStatsRequest(buf []byte, offset flatbuffers.UOffsetT) *GetStatsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetStatsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetStatsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetStatsRequest(buf []byte, offset flatbuffers.UOffsetT) *GetStatsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetStatsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetStatsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetStatsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetStatsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func GetStatsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GetStatsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
