// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetTransactionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetTransactionRequest(buf []byte, offset flatbuffers.UOffsetT) *GetTransactionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetTransactionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetTransactionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetTransactionRequest(buf []byte, offset flatbuffers.UOffsetT) *GetTransactionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetTransactionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetTransactionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetTransactionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetTransactionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetTransactionRequest) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetTransactionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetTransactionRequestAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func GetTransactionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
