// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PendingTransactionsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPendingTransactionsResponse(buf []byte, offset flatbuffers.UOffsetT) *PendingTransactionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PendingTransactionsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPendingTransactionsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPendingTransactionsResponse(buf []byte, offset flatbuffers.UOffsetT) *PendingTransactionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PendingTransactionsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPendingTransactionsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PendingTransactionsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PendingTransactionsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PendingTransactionsResponse) Transactions() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PendingTransactionsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PendingTransactionsResponseAddTransactions(builder *flatbuffers.Builder, transactions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(transactions), 0)
}
func PendingTransactionsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
