// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsStatsResponse(buf []byte, offset flatbuffers.UOffsetT) *StatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatsResponse(buf []byte, offset flatbuffers.UOffsetT) *StatsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatsResponse) Stats() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StatsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatsResponseAddStats(builder *flatbuffers.Builder, stats flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stats), 0)
}
func StatsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
