// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransactionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTransactionResponse(buf []byte, offset flatbuffers.UOffsetT) *TransactionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransactionResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransactionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransactionResponse(buf []byte, offset flatbuffers.UOffsetT) *TransactionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransactionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransactionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransactionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransactionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransactionResponse) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TransactionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransactionResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func TransactionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
