// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package thrylos

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransactionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTransactionRequest(buf []byte, offset flatbuffers.UOffsetT) *TransactionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransactionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransactionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransactionRequest(buf []byte, offset flatbuffers.UOffsetT) *TransactionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransactionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransactionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransactionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransactionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransactionRequest) Transaction(obj *Transaction) *Transaction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Transaction)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TransactionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransactionRequestAddTransaction(builder *flatbuffers.Builder, transaction flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(transaction), 0)
}
func TransactionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
