[package]
name = "chain-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Storage, pruning, snapshots"

[lints]
workspace = true

[dependencies]
chain-engine-api = { path = "../chain-engine-api", version = "0.1.0" }
chain-state = { path = "../chain-state", version = "0.1.0" }
chain-types = { path = "../chain-types", version = "0.1.0" }
libmdbx.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true
tempfile.workspace = true
