[package]
name = "chain-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Block executor wrapping MoveVM"

[lints]
workspace = true

[dependencies]
chain-engine-api = { path = "../chain-engine-api", version = "0.1.0" }
chain-modules = { path = "../chain-modules", version = "0.1.0" }
chain-state = { path = "../chain-state", version = "0.1.0" }
chain-types = { path = "../chain-types", version = "0.1.0" }
move-binary-format.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-runtime.workspace = true
tempfile.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true
